### ISSUE TITLE
Arb key with select generated code throws error

### ISSUE THREAD

**Issue by Merculiar** [localizely/flutter-intl-intellij#95] opened 2023-04-18 11:31 UTC
Select generated code throws an error - The argument type 'dynamic' can't be assigned to the parameter type 'String'
The code is taken from the example of the plugin.
Select in arb: 
<img width="636" alt="Screenshot 2023-04-18 at 14 27 32" src="https://user-images.githubusercontent.com/46864104/232763800-ef5d9b2a-d8e2-4141-9cb8-2cf2a72020aa.png">

Generated String:
<img width="876" alt="Screenshot 2023-04-18 at 14 27 24" src="https://user-images.githubusercontent.com/46864104/232763885-dc51732d-9aca-4d5a-9c5c-cb5898eb6b65.png">
Red error is annoying.

**Comment by lzoran** [comment] 2023-04-24 12:48
Hi @Merculiar,

I believe that you have `implicit-casts` set to `false` in the `analysis_options.yaml` file. If that is the case, perhaps excluding the generated files from the Dart Analysis might help.

The `analysis_options.yaml` file
```
analyzer:
  exclude: [lib/generated/**]
  strong-mode:
    implicit-casts: false
```

Hope it helps!

**Comment by lzoran** [comment] 2023-04-24 12:49
Duplicate of [#7](https://github.com/localizely/flutter-intl-intellij/issues/7).

**Comment by lzoran** [comment] 2023-04-24 12:51
Closing this issue as a duplicate.
In case I missed something, feel free to open this issue again.

**Closed as completed by lzoran** 2023-04-24 12:51 UTC
Labels: duplicate
