### ISSUE TITLE
Invalid internationalization in package

### ISSUE THREAD

**Issue by lizhuoyuan** [localizely/flutter-intl-intellij#50] opened 2020-12-10 12:40 UTC
The project relies on its own package, but the internationalization in the package is invalid, and the current language can be obtained, but the value is based on the default language.

```


 localeResolutionCallback: (Locale locale, Iterable<Locale> supportedLocales) {
        print('deviceLocale: $locale');
        print('supportedLocales: $supportedLocales');
        print('languageCode:${locale?.languageCode}');
        print('scriptCode:${locale?.scriptCode}');

        // Chinese simplified and traditional processing
        if (locale?.languageCode == 'zh') {
          if (locale?.scriptCode == 'Hant') {
            return Locale('zh', 'HK'); 
          } else {
            return Locale('zh', 'CN');
          }
        }
```
```
I/flutter (27941): deviceLocale: zh_Hans_CN
I/flutter (27941): supportedLocales: [en, zh_CN, zh_HK]
I/flutter (27941): languageCode:zh
I/flutter (27941): scriptCode:Hans
```
yaml:
```
  cece_login_module:
    path: ../cece_login_module
```
But the language used in the cece_login_module is still English.
cece_login_module Multilingual is ok.

```
  /// `GO FIRST oo`
  String get goFirst {
    return Intl.message(
      'GO FIRST o1111o',
      name: 'goFirst',
      desc: '',
      args: [],
    );
  }
```
Always return 'GO FIRST o1111o', not the result of any language.

**Comment by lzoran** [comment] 2020-12-10 17:42
Hi @lizhuoyuan,

Thanks for reporting this!

I see you are using a modular approach for your app. Have you checked this [issue](https://github.com/localizely/flutter-intl-intellij/issues/22), maybe there is something useful?
Could you give us some kind of a minimal working example, so we can check where it might be the problem?

**Comment by lizhuoyuan** [comment] 2020-12-11 00:55
thanks,i will try

**Comment by lizhuoyuan** [comment] 2020-12-14 04:00
https://github.com/lizhuoyuan/flutter_intl_example

this is an example,no matter how you modify the locale, the text in the module is the default value
![2020-12-14 11 58 55](https://user-images.githubusercontent.com/15923901/102039097-dee05580-3e03-11eb-8f80-3ea971e80deb.gif)

**Comment by lzoran** [comment] 2020-12-15 11:16
Hi @lizhuoyuan,

Thanks for the example!
You are right, it is the same problem. The Intl library initializes only the first set of translations.
I'll close this issue as it is a duplicate of the [#22](https://github.com/localizely/flutter-intl-intellij/issues/22).

**Closed by lzoran** 2020-12-15 11:16 UTC
Labels: duplicate
