### ISSUE TITLE
compile error when no space

### ISSUE THREAD

**Issue by jerry90** [localizely/flutter-intl-intellij#1] opened 2020-01-21 01:13 UTC
![1579568955990](https://user-images.githubusercontent.com/11992901/72767124-f633b480-3c2d-11ea-8a94-f5ac2d49741a.jpg)
![1579569010429](https://user-images.githubusercontent.com/11992901/72767128-fdf35900-3c2d-11ea-820c-5c0e4c449d1b.jpg)
suggest
![1579569048641](https://user-images.githubusercontent.com/11992901/72767133-051a6700-3c2e-11ea-9677-304181256486.jpg)

**Comment by aleksakrstic** [comment] 2020-01-21 17:26
@jerry90 Thanks for the detailed explanation of the issue!

The issue is fixed now with versions `1.0.1` and `1.1.1`, in a way you suggested.

**Closed by aleksakrstic** 2020-01-21 17:26 UTC
