### ISSUE TITLE
Recreating in wrong folder

### ISSUE THREAD

**Issue by degloff** [localizely/flutter-intl-intellij#12] opened 2020-03-12 13:18 UTC
After some modifications the plugin failed to recognise the languages and always recreates new one in the folder android/lib/i8n instead of lib/i8n. As it is closed source I have no clue what is going on.

**Comment by degloff** [comment] 2020-03-12 13:22
This makes actually localizelly totally useless and I have to find an alternative

**Comment by goranluledzija** [comment] 2020-03-12 23:22
Hi @degloff 
We didn't succeed to reproduce the issue after many attempts.
Additional info for reproduction would be really appreciated.

In theory what might have happened by doing code analyses: 
IDE somehow reordered modules in the project (Flutter project as a root module and "android" folder as an additional module). Probably restart of IDE could solve it on its own, just before restarting make sure your root folder is recognized as a Flutter project.

**Comment by goranluledzija** [comment] 2020-03-17 21:13
Closing this issue due to a lack of reproduction info.

However, with plugin version `1.4.0` prevention for potential cause is released.
In a case this issue still happens, please open a new one.

**Closed by goranluledzija** 2020-03-17 21:13 UTC
