### ISSUE TITLE
updating the auto generated files takes too long

### ISSUE THREAD

**Issue by KorbinianMossandl** [localizely/flutter-intl-intellij#32] opened 2020-07-03 14:18 UTC
Is there a way to speed up the generation/updating of the auto generated files when editing the .arb files?
It can sometimes take 1-2 minutes which is a pain when adding strings "on the go" for new UI elements.

**Comment by aleksakrstic** [comment] 2020-07-03 19:36
Hi @KorbinianMossandl 
Hmm, for us it takes up to 4-5s, but not more than 10s in the worst case.
Could you give us more info, like:
- IDE version
- Flutter Intl plugin version
- Number of arb files in the project
- Number of string keys inside the main arb file
- Operating System (Mac/Windows/Linux)
- CPU & RAM info

**Comment by KorbinianMossandl** [comment] 2020-07-03 22:36
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Flutter Intl 1.8.1-2019.2
2 arb files roughly 400 strings each
Linux 4.15.0-109-generic
Intel Core i7-8700K
32 GB DDR4

**Comment by aleksakrstic** [comment] 2020-07-10 18:48
Hi @KorbinianMossandl 
We tried to reproduce slow performances but without success. 
Code generation lasts less than 5s in all tried cases.

Could you test performances on your machine again, but with the project in attached zip file?
[flutter_demo.zip](https://github.com/localizely/flutter-intl-intellij/files/4904825/flutter_demo.zip)

**Comment by aleksakrstic** [comment] 2020-11-08 12:46
Closing this issue since no feedback

**Closed by aleksakrstic** 2020-11-08 12:46 UTC
