### ISSUE TITLE
generate failed

### ISSUE THREAD

**Issue by JohnGuSir** [localizely/flutter-intl-intellij#108] opened 2023-09-12 03:24 UTC
/Users/john/Library/flutter/bin/flutter --no-color pub global run intl_utils:generate
Failed to build intl_utils:generate:
../../../../.pub-cache/hosted/pub.flutter-io.cn/watcher-1.0.2/lib/src/constructable_file_system_event.dart:7:57: Error: The class 'FileSystemEvent' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _ConstructableFileSystemEvent implements FileSystemEvent {

<img width="428" alt="image" src="https://github.com/localizely/flutter-intl-intellij/assets/75824046/ec7eb606-095d-437b-afb8-58198ca53237">
<img width="556" alt="image" src="https://github.com/localizely/flutter-intl-intellij/assets/75824046/0c94ba3e-bb7c-4add-9189-5c61de2cab10">

**Comment by JohnGuSir** [comment] 2023-09-12 03:32
intl: ^0.18.1

**Comment by DogTwoChen** [comment] 2023-09-12 07:14
flutter pub global deactivate intl_utils
flutter pub global activate intl_utils

**Comment by JohnGuSir** [comment] 2023-09-12 08:29
thanks

**Comment by lzoran** [comment] 2023-09-12 09:04
Duplicate of the [#105](https://github.com/localizely/flutter-intl-intellij/issues/105).

Closing as resolved.
In case of any irregularities, feel free to open it again.

**Closed as completed by lzoran** 2023-09-12 09:04 UTC
Labels: duplicate
