### ISSUE TITLE
How to use inside a library and an app at the same time?

### ISSUE THREAD

**Issue by StevenMagdy** [localizely/flutter-intl-intellij#27] opened 2020-06-01 04:18 UTC
I have a library and an app which depends on the library, I tried to use this tool to localize both projects, However, when running only the library got translated.
How to solve this issue? is it Intl related?

**Comment by aleksakrstic** [comment] 2020-06-02 20:18
Hi @StevenMagdy 
I assume you open library and app in different AndroidStudio windows (projects).
Could you try with having Localization Delegate and ARB files inside your library, for the localization content it contains.
For app you could have separate Localization Delegate generated from the separate ARB files.

And then when using your library from the app, potentially to pass extended library's delegate if you want to overwrite its content. 

Something similar to default delegates for `MaterialApp` and your custom code that uses it as library.

I hope this helps. Otherwise I think I can not help more without provided code or relevant project structure

**Comment by StevenSorial** [comment] 2020-06-03 04:51
I'm already using two different delegates, but apparently the Intl package doesn't support multiple sets of translations ([issue](https://github.com/dart-lang/i18n/issues/358)), so I turned off the plugin in the library and used the workaround mentioned [here](https://medium.com/@gerrel/flutter-package-with-intl-localization-394e9da1164a?source=friends_link&sk=48169f60f86aef7eb38bf0fe43041574).

**Comment by aleksakrstic** [comment] 2020-06-16 20:17
Hi @StevenMagdy 
You are correct, Intl does not support it and it is a blocker. 

It is the best to turn off the plugin for library project and write localization code manually there without Intl library. And use the plugin for app project only.

We will see where Intl library will go in the future and will try to find more elegant solution.

**Comment by aleksakrstic** [comment] 2020-06-16 20:22
Duplicate of https://github.com/localizely/flutter-intl-intellij/issues/22

**Closed by aleksakrstic** 2020-06-16 20:22 UTC
Labels: duplicate
