### ISSUE TITLE
Plural messages should use `num` not `dynamic`.

### ISSUE THREAD

**Issue by maguro** [localizely/flutter-intl-intellij#20] opened 2020-04-01 18:35 UTC
The Dart function `Intl.plural()` takes a `num`.  The plugin generates functions that take `dynamic`.  This causes no end of linting noise.

**Comment by knaeckeKami** [comment] 2020-04-01 18:38
This should be fixed in the latest release of the plugin, v1.4.1

**Comment by aleksakrstic** [comment] 2020-04-01 20:44
Duplicate of https://github.com/localizely/flutter-intl-intellij/issues/7

**Closed by aleksakrstic** 2020-04-01 20:44 UTC
Labels: duplicate
